name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]
    name: Node.js ${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm ci
      - run: npm run prepublishOnly
      - uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            lib/
            umd/

  edge-runtime:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: runtimes/edge/package-lock.json
      - id: client-deps
        uses: actions/cache@v3
        with:
          path: |
            ./node_modules
          key: ${{ runner.os }}-dependencies-${{ hashFiles('package-lock.json') }}
      - if: steps.client-deps.outputs.cache-hit != 'true'
        run: npm install --omit=dev --ignore-scripts
      - uses: actions/download-artifact@v3
        with:
          name: build-output
      - run: npm ci
        working-directory: ./runtimes/edge
      - run: npm test
        working-directory: ./runtimes/edge
